# CareerLens AI
Notebook 01 – Technology Job Market Data Exploration

##🎯 Objective
The objective of this notebook is to explore and understand the Technology Job Market dataset before any preprocessing or analysis is performed.

This exploration focuses on examining the dataset structure, identifying available attributes, assessing data quality, understanding career distribution, and evaluating the suitability of the dataset for developing the CareerLens AI recommendation system.

The insights obtained during this phase will guide subsequent preprocessing, feature engineering, and analytical tasks.

##📌 Project Background
CareerLens AI is an AI-powered career intelligence platform designed to bridge the gap between academic education and industry requirements.

The platform analyzes real-world technology job postings to identify market demand, required skills, career trends, and learning pathways for university students, fresh graduates, and entry-level IT professionals.

This notebook represents the first stage of the analytical workflow by exploring the raw dataset before any transformations are applied.

## 📊 Dataset Information

| Attribute | Value |
|-----------|-------|
| **Dataset** | Technology Job Market Dataset |
| **Source** | Kaggle |
| **Original Records** | 1,615,940 |
| **Features** | 23 |
| **Primary Language** | English |
| **Coverage** | Multiple industries and job categories |

##🐍 Section 1 — Import Libraries

In [24]:
import pandas as pd
import numpy as np

# Display all columns
pd.set_option("display.max_columns", None)

##📂 Section 2 — Load Dataset

In [25]:
#Mount the google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [26]:
#Load dataset
file_path = "/content/drive/MyDrive/CareerLensAI/job_descriptions.csv"

df = pd.read_csv(file_path)
df.head()

,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,Company Size,Job Posting Date,Preference,Contact Person,Contact,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,54.2361,-4.5481,Intern,26801,2022-04-24,Female,Brandon Cunningham,001-381-930-7517x737,Digital Marketing Specialist,Social Media Manager,Snagajob,Social Media Managers oversee an organizations...,"{'Flexible Spending Accounts (FSAs), Relocatio...","Social media platforms (e.g., Facebook, Twitte...","Manage and grow social media accounts, create ...",Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversifie..."
1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,38.9697,59.5563,Intern,100340,2022-12-19,Female,Francisco Larsen,461-509-4216,Web Developer,Frontend Web Developer,Idealist,Frontend Web Developers design and implement u...,"{'Health Insurance, Retirement Plans, Paid Tim...","HTML, CSS, JavaScript Frontend frameworks (e.g...","Design and code user interfaces for websites, ...",PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Com..."
2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",22.1987,113.5439,Temporary,84525,2022-09-14,Male,Gary Gibson,9687619505,Operations Manager,Quality Control Manager,Jobs2Careers,Quality Control Managers establish and enforce...,"{'Legal Assistance, Bonuses and Incentive Prog...",Quality control processes and methodologies St...,Establish and enforce quality control standard...,United Services Automobile Assn.,"{""Sector"":""Insurance"",""Industry"":""Insurance: P..."
3,688192671473044,4 to 11 Years,PhD,$65K-$91K,Porto-Novo,Benin,9.3077,2.3158,Full-Time,129896,2023-02-25,Female,Joy Lucero,+1-820-643-5431x47576,Network Engineer,Wireless Network Engineer,FlexJobs,"Wireless Network Engineers design, implement, ...","{'Transportation Benefits, Professional Develo...",Wireless network design and architecture Wi-Fi...,"Design, configure, and optimize wireless netwo...",Hess,"{""Sector"":""Energy"",""Industry"":""Mining, Crude-O..."
4,117057806156508,1 to 12 Years,MBA,$64K-$87K,Santiago,Chile,-35.6751,-71.5429,Intern,53944,2022-10-11,Female,Julie Johnson,343.975.4702x9340,Event Manager,Conference Manager,Jobs2Careers,A Conference Manager coordinates and manages c...,"{'Flexible Spending Accounts (FSAs), Relocatio...",Event planning Conference logistics Budget man...,Specialize in conference and convention planni...,Cairn Energy,"{""Sector"":""Energy"",""Industry"":""Energy - Oil & ..."

##📏 Section 3 — Dataset Dimensions

In [27]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.shape

Rows: 1615940
Columns: 23

(1615940, 23)

##📋 Section 4 — Dataset Structure

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1615940 entries, 0 to 1615939
Data columns (total 23 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Job Id            1615940 non-null  int64
 1   Experience        1615940 non-null  object
 2   Qualifications    1615940 non-null  object
 3   Salary Range      1615940 non-null  object
 4   location          1615940 non-null  object
 5   Country           1615940 non-null  object
 6   latitude          1615940 non-null  float64
 7   longitude         1615940 non-null  float64
 8   Work Type         1615940 non-null  object
 9   Company Size      1615940 non-null  int64
 10  Job Posting Date  1615940 non-null  object
 11  Preference        1615940 non-null  object
 12  Contact Person    1615940 non-null  object
 13  Contact           1615940 non-null  object
 14  Job Title         1615940 non-null  object
 15  Role              1615940 non-null  object
 16  Job Portal        1615940 non-null  object
 17  Job Description   1615940 non-null  object
 18  Benefits          1615940 non-null  object
 19  skills            1615940 non-null  object
 20  Responsibilities  1615940 non-null  object
 21  Company           1615940 non-null  object
 22  Company Profile   1610462 non-null  object
dtypes: float64(2), int64(2), object(19)
memory usage: 283.6+ MB

##🏷️ Section 5 — Column Overview

In [29]:
df.columns

Index(['Job Id', 'Experience', 'Qualifications', 'Salary Range', 'location',
       'Country', 'latitude', 'longitude', 'Work Type', 'Company Size',
       'Job Posting Date', 'Preference', 'Contact Person', 'Contact',
       'Job Title', 'Role', 'Job Portal', 'Job Description', 'Benefits',
       'skills', 'Responsibilities', 'Company', 'Company Profile'],
      dtype='object')

##❗ Section 6 — Missing Value Analysis

In [31]:
missing_values = df.isnull().sum()

missing_values[missing_values > 0]

#The dataset is highly complete. Only the Company Profile attribute contains missing values, while the remaining features have no missing records

Company Profile    5478
dtype: int64

##🔍 Section 7 — Data Types

In [32]:
df.dtypes.value_counts()

object     19
int64       2
float64     2
Name: count, dtype: int64

##💼 Section 8 — Unique Job Roles

In [33]:
print("Unique Roles:", df["Role"].nunique())

Unique Roles: 376

In [34]:
df["Role"].value_counts().head(20)

Role
Interaction Designer         20580
Network Administrator        17470
User Interface Designer      14036
Social Media Manager         13945
User Experience Designer     13935
Procurement Analyst          13757
Social Media Analyst         10659
Quality Assurance Analyst    10541
SEO Specialist               10512
Executive Assistant          10496
Database Administrator       10482
Procurement Manager          10407
Data Analyst                 10406
Backend Developer            10404
Demand Planner               10362
Office Manager               10361
Customer Success Manager     10308
Frontend Developer           10308
Retirement Planner           10305
Account Executive             7063
Name: count, dtype: int64

##💡 Section 9 — Initial Observations



*   The dataset contains over 1.6 million job postings, making it suitable for large-scale labor market analysis.
*   Most attributes are categorical, indicating that text-based analysis and feature engineering will play a significant role.
* The dataset spans multiple industries, requiring domain-specific filtering before technology-focused analysis.
* Skills, job descriptions, and responsibilities provide rich textual data for future NLP and recommendation tasks.
* The dataset contains geographical, educational, and experience-related information that can support deeper market analysis.

##🚀 Section 10 — Summary & Next Steps

This notebook explored the structure and characteristics of the Technology Job Market dataset.

The findings confirmed that the dataset is suitable for developing CareerLens AI after appropriate preprocessing.

Next Steps

* Identify technology-related careers.
* Filter the dataset to technology job postings.
* Create career domain classifications.
* Generate a processed dataset for downstream analysis.